language: cpp
compiler: gcc
sudo: false

addons:
  apt:
    packages:
      - qemu

before_script:
  - node -e "console.log('test')"
  - node -v
  - qemu-system-x86_64 -version

script: "npm install runtimejs runtimeify && npm test"
