language: node_js
sudo: false

script:
  - npm run start2

addons:
  apt:
    packages:
      - xvfb
      - qemu
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
